#!/usr/bin/env python3

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from tempfile import NamedTemporaryFile


ROOT = Path(__file__).resolve().parents[1]


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "claude-delegation"


def render_plan(
    *,
    task_id: str,
    owner: str,
    status: str,
    goal: str,
    required_changes: list[str],
    forbidden_changes: list[str],
    constraints: list[str],
    verification: list[str],
    claude_work_items: list[str],
) -> str:
    timestamp = datetime.now(timezone.utc).date().isoformat()

    scope_lines = ["- files expected to change:"]
    if required_changes:
        scope_lines.extend(f"  - {item}" for item in required_changes)
    else:
        scope_lines.append("  - determine the smallest necessary change set for the stated goal")

    scope_lines.append("- files that must not change:")
    if forbidden_changes:
        scope_lines.extend(f"  - {item}" for item in forbidden_changes)
    else:
        scope_lines.append("  - unrelated files")

    scope_lines.append("- public interfaces that must remain stable:")
    if constraints:
        scope_lines.extend(f"  - {item}" for item in constraints)
    else:
        scope_lines.append("  - existing public interfaces unless the goal explicitly requires a change")

    scope_lines.append("- dependencies or tools that may be missing locally:")
    scope_lines.append("  - report any missing tool instead of silently skipping it")

    validation_lines = verification or [
        "run the smallest relevant repo-local checks for the touched area",
        "report skipped checks and why",
        "state whether files stayed in scope",
    ]

    claude_lines = claude_work_items or required_changes or [
        "execute the smallest bounded change set that satisfies the goal"
    ]

    return "\n".join(
        [
            "# Delegated Claude Plan",
            "",
            "## Metadata",
            "",
            f"- task_id: {task_id}",
            f"- status: {status}",
            f"- owner: {owner}",
            f"- last_updated: {timestamp}",
            "",
            "## Problem",
            "",
            goal,
            "",
            "## Context",
            "",
            "- generated by `scripts/delegate_to_claude.py` for a bounded Codex -> Claude delegation",
            f"- repository root: `{ROOT}`",
            "",
            "## Scope",
            "",
            *scope_lines,
            "",
            "## Milestones",
            "",
            "1. [ ] Restate the scope before editing.",
            "2. [ ] Execute the bounded task in Claude Code.",
            "3. [ ] Report changed files, checks run, skipped checks, and residual issues.",
            "",
            "## Claude Work Items",
            "",
            *[f"- {item}" for item in claude_lines],
            "",
            "## Validation Strategy",
            "",
            *[f"- {item}" for item in validation_lines],
            "",
            "## Risks",
            "",
            "- do not widen scope without Codex review",
            "- do not treat Claude output as accepted until Codex validates the result",
            "",
            "## Execution Notes",
            "",
            "- temporary plan generated for direct Codex delegation",
            "",
            "## Exit Criteria",
            "",
            "- Claude returns a bounded execution summary suitable for Codex validation",
        ]
    ) + "\n"


def write_plan(plan_text: str, explicit_path: str | None, task_id: str) -> Path:
    if explicit_path:
        plan_path = Path(explicit_path)
        if not plan_path.is_absolute():
            plan_path = ROOT / plan_path
        plan_path.parent.mkdir(parents=True, exist_ok=True)
        plan_path.write_text(plan_text, encoding="utf-8")
        return plan_path.resolve()

    temp_dir = Path("/tmp/claude-agent-setup-delegations")
    temp_dir.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        prefix=f"{task_id}-",
        suffix=".md",
        dir=temp_dir,
        delete=False,
    ) as handle:
        handle.write(plan_text)
        return Path(handle.name).resolve()


def run_bridge(plan_path: Path, permission_mode: str, claude_bin: str) -> int:
    command = [
        "python3",
        str(ROOT / "scripts" / "run_claude_from_plan.py"),
        str(plan_path),
        "--permission-mode",
        permission_mode,
        "--claude-bin",
        claude_bin,
    ]
    completed = subprocess.run(command, cwd=ROOT, check=False)
    return completed.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a bounded plan and delegate it to Claude.")
    parser.add_argument("--goal", required=True, help="Clear goal for Claude.")
    parser.add_argument("--change", action="append", default=[], help="Required change item. Repeatable.")
    parser.add_argument("--forbid", action="append", default=[], help="Forbidden file or category. Repeatable.")
    parser.add_argument("--constraint", action="append", default=[], help="Constraint or public-interface rule. Repeatable.")
    parser.add_argument("--verify", action="append", default=[], help="Validation command or rule. Repeatable.")
    parser.add_argument("--work-item", action="append", default=[], help="Explicit Claude work item. Repeatable.")
    parser.add_argument("--task-id", help="Explicit task id. Defaults to a slugified goal.")
    parser.add_argument("--owner", default="Codex", help="Plan owner. Defaults to Codex.")
    parser.add_argument(
        "--status",
        default="active",
        choices=["proposed", "active", "blocked", "completed"],
        help="Plan status. Defaults to active.",
    )
    parser.add_argument("--plan-file", help="Optional path to persist the generated plan inside or outside the repo.")
    parser.add_argument(
        "--permission-mode",
        default="acceptEdits",
        help="Claude permission mode for the delegated run. Defaults to acceptEdits.",
    )
    parser.add_argument("--claude-bin", default="claude", help="Claude CLI executable.")
    parser.add_argument("--print-plan", action="store_true", help="Print the generated plan and exit.")
    parser.add_argument("--print-brief", action="store_true", help="Print the generated Claude brief and exit.")
    parser.add_argument("--plan-only", action="store_true", help="Write the plan and print its path without invoking Claude.")
    args = parser.parse_args()

    task_id = args.task_id or slugify(args.goal)
    plan_text = render_plan(
        task_id=task_id,
        owner=args.owner,
        status=args.status,
        goal=args.goal,
        required_changes=args.change,
        forbidden_changes=args.forbid,
        constraints=args.constraint,
        verification=args.verify,
        claude_work_items=args.work_item,
    )

    if args.print_plan:
        sys.stdout.write(plan_text)
        return 0

    plan_path = write_plan(plan_text, args.plan_file, task_id)
    sys.stdout.write("## Delegate Runner\n")
    sys.stdout.write(f"- task_id: {task_id}\n")
    sys.stdout.write(f"- plan: {plan_path}\n")
    sys.stdout.write(f"- permission_mode: {args.permission_mode}\n")
    sys.stdout.flush()

    if args.plan_only:
        return 0

    if args.print_brief:
        command = [
            "python3",
            str(ROOT / "scripts" / "run_claude_from_plan.py"),
            str(plan_path),
            "--print-brief",
        ]
        completed = subprocess.run(command, cwd=ROOT, check=False)
        return completed.returncode

    sys.stdout.write("- action: invoking Claude bridge\n\n")
    sys.stdout.flush()
    return run_bridge(plan_path, args.permission_mode, args.claude_bin)


if __name__ == "__main__":
    raise SystemExit(main())
